# -*- coding: utf-8 -*-
"""Linear1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HStSRp9vU7KcEcyfQ5Awb9NhczB9OlOZ
"""

import numpy as np
import pandas as pd

wine_data = pd.read_csv("winequality-red.csv")

wine_data.head()
wine_data.shape

wine_data.info()

wine_data.describe()

wine_data.isnull().sum()

X_alcohol = wine_data[['alcohol']]
y = wine_data['quality']

import sklearn.model_selection as model_selection
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_alcohol, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred

print(model.score(X_test, y_test))

from sklearn.metrics import mean_squared_error, mean_absolute_error

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
plt.scatter(X_test, y_test)
plt.plot(X_test, y_pred)
plt.xlabel("Alcohol")
plt.ylabel("Wine Quality")
plt.title("Best Fit Line: Alcohol vs Wine Quality")
plt.show()