# -*- coding: utf-8 -*-
"""Gradient_Descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3NIDQeRbWZit2aPNOWpR9__D7hepg8b
"""

import numpy as np

X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

m = 0
c = 0

learning_rate = 0.01
epochs = 20

n = len(X)

for i in range(epochs):

    y_pred = m * X + c

    error = y_pred - y

    dm = (2/n) * np.sum(X * error)
    dc = (2/n) * np.sum(error)

    m = m - learning_rate * dm
    c = c - learning_rate * dc

    print("Iteration:", i + 1)
    print("m =", m)
    print("c =", c)
    print()

x_test = 6
prediction = m * x_test + c

print("Prediction for x = 6 is:", prediction)